packages:
  - packages*/**
# https://pnpm.io/zh/catalogs
catalog:
  "@commitlint/cli": ^19.6.1
  "@commitlint/config-conventional": ^19.6.0
  "@eslint/js": ^9.17.0
  "@stylistic/stylelint-plugin": ^3.1.1
  "@types/eslint": ^9.6.1
  "@typescript-eslint/eslint-plugin": ^8.19.1
  "@typescript-eslint/parser": ^8.19.1
  commitlint-plugin-function-rules: ^4.0.1
  cz-git: ^1.11.0
  czg: ^1.11.0
  eslint: ^9.17.0
  eslint-plugin-command: ^2.1.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsdoc: ^50.6.1
  eslint-plugin-jsonc: ^2.18.2
  eslint-plugin-perfectionist: ^4.6.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^9.32.0
  globals: ^15.14.0
  husky: ^9.1.7
  jsonc-eslint-parser: ^2.4.0
  postcss: ^8.4.49
  postcss-html: ^1.7.0
  prettier: ^3.4.2
  stylelint: ^16.12.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  vue-eslint-parser: ^9.4.3
