packages:
  - packages*/**
catalog:
  "@ant-design/v5-patch-for-react-19": ^1.0.3
  "@arco-design/web-react": ^2.65.0
  "@arco-design/web-vue": ^2.56.3
  "@babel/generator": ^7.26.9
  "@babel/parser": ^7.26.9
  "@babel/traverse": ^7.26.9
  "@changesets/cli": ^2.28.1
  "@chromatic-com/storybook": ^3
  "@codemirror/lang-json": ^6.0.1
  "@codemirror/lang-vue": ^0.1.3
  "@codemirror/state": ^6.5.1
  "@codemirror/view": ^6.36.2
  "@commitlint/cli": ^19.6.1
  "@commitlint/config-conventional": ^19.6.0
  "@eslint/js": ^9.17.0
  "@storybook/addon-essentials": ^8.6.7
  "@storybook/addon-interactions": ^8.6.7
  "@storybook/addon-onboarding": ^8.6.7
  "@storybook/blocks": ^8.6.7
  "@storybook/experimental-addon-test": ^8.6.4
  "@storybook/manager-api": ^8.5.0
  "@storybook/react": ^8.6.7
  "@storybook/react-vite": ^8.6.7
  "@storybook/test": ^8.6.7
  "@storybook/vue3": ^8.5.0
  "@storybook/vue3-vite": ^8.5.0
  "@stylistic/eslint-plugin": ^2.13.0
  "@stylistic/eslint-plugin-ts": ^2.13.0
  "@stylistic/stylelint-plugin": ^3.1.1
  "@tsconfig/node22": ^22.0.0
  "@types/css-modules": ^1.0.5
  "@types/eslint": ^9.6.1
  "@types/glob": ^8.1.0
  "@types/node": ^22.13.4
  "@types/react": ^19.0.10
  "@typescript-eslint/eslint-plugin": ^8.19.1
  "@typescript-eslint/parser": ^8.19.1
  "@vitejs/plugin-react": ^4.3.4
  "@vitejs/plugin-vue": ^5.2.1
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "@vitest/browser": ^3.0.8
  "@vitest/coverage-v8": ^3.0.8
  "@vue/compiler-sfc": ^3.5.13
  "@vue/eslint-config-typescript": ^14.2.0
  "@vue/tsconfig": ^0.7.0
  ajv: ^8.17.1
  antd: ^5.24.3
  codemirror: ^6.0.1
  commitlint-plugin-function-rules: ^4.0.1
  cspell: ^8.17.2
  csstype: ^3.1.3
  cz-git: ^1.11.0
  czg: ^1.11.0
  depcheck: ^1.4.7
  element-plus: ^2.9.4
  eslint: ^9.18.0
  eslint-plugin-command: ^2.1.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsdoc: ^50.6.1
  eslint-plugin-jsonc: ^2.18.2
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-oxlint: ^0.15.6
  eslint-plugin-perfectionist: ^4.6.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-compiler: 19.0.0-beta-40c6c23-20250301
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^9.32.0
  glob: ^11.0.1
  globals: ^15.14.0
  husky: ^9.1.7
  jsonc-eslint-parser: ^2.4.0
  lerna: ^8.1.9
  lint-staged: ^15.3.0
  markdown-it-container: ^4.0.0
  markdownlint-cli2: ^0.17.1
  npm-package-json-lint: ^8.0.0
  npm-package-json-lint-config-default: ^7.0.1
  npm-run-all2: ^7.0.2
  only-allow: ^1.2.1
  pinia: ^2.3.0
  playwright: ^1.51.0
  postcss: ^8.4.49
  postcss-html: ^1.7.0
  prettier: ^3.4.2
  react: ^19.0.0
  react-dom: ^19.0.0
  rollup-plugin-visualizer: ^5.14.0
  sass-embedded: ^1.85.1
  storybook: ^8.6.7
  stylelint: ^16.12.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  typescript: ^5.8.2
  typescript-eslint: ^8.20.0
  vite: ^6.2.1
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-dts: ^4.5.3
  vite-plugin-vue-devtools: ^7.6.8
  vitepress: ^1.6.3
  vitepress-demo-plugin: ^1.3.1
  vitest: ^3.0.8
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
